// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvdq1IHWFJ4QpNzszrJnYuPVw4M2iPN5c',
    appId: '1:427624094170:web:a306db5e921149da6a88e3',
    messagingSenderId: '427624094170',
    projectId: 'zeeyou-164ed',
    authDomain: 'zeeyou-164ed.firebaseapp.com',
    storageBucket: 'zeeyou-164ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyTJpGg7vsz8QzICrBqCYn2wvI2sbB68M',
    appId: '1:427624094170:android:5c775835f8d9d0b76a88e3',
    messagingSenderId: '427624094170',
    projectId: 'zeeyou-164ed',
    storageBucket: 'zeeyou-164ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYjiuF73kM5qC62YrJ7IF1A7aaQWCfN4o',
    appId: '1:427624094170:ios:c30f91c27f24eb616a88e3',
    messagingSenderId: '427624094170',
    projectId: 'zeeyou-164ed',
    storageBucket: 'zeeyou-164ed.appspot.com',
    iosClientId: '427624094170-si9cies1bqsp9hcjbgngtmmdblfudebj.apps.googleusercontent.com',
    iosBundleId: 'com.example.zeeyou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYjiuF73kM5qC62YrJ7IF1A7aaQWCfN4o',
    appId: '1:427624094170:ios:796c109b34b526e36a88e3',
    messagingSenderId: '427624094170',
    projectId: 'zeeyou-164ed',
    storageBucket: 'zeeyou-164ed.appspot.com',
    iosClientId: '427624094170-8jvqhhj3h0bndneh6koc5uk5urj8mac7.apps.googleusercontent.com',
    iosBundleId: 'com.example.zeeyou.RunnerTests',
  );
}
